package io.github.jaffe2718.petprofile.mcp;

import android.content.Context;

import com.google.gson.JsonObject;
import com.google.gson.JsonParser;

import java.io.BufferedInputStream;
import java.io.BufferedOutputStream;
import java.io.IOException;
import java.io.OutputStream;
import java.net.InetSocketAddress;
import java.net.ServerSocket;
import java.net.Socket;
import java.nio.charset.StandardCharsets;
import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

import io.github.jaffe2718.petprofile.util.NetworkUtil;

/**
 * Minimal streamable-http MCP server for the PetProfile data. It exposes a single JSON-RPC
 * endpoint at {@code /petprofile} and authenticates every request with a {@code Bearer} token
 * generated by {@link McpTokenManager}. Responses are single JSON-RPC messages (no SSE), which is
 * within the MCP streamable-http transport contract for non-streaming tool calls.
 */
public final class McpServer {
    private static final String PROTOCOL_VERSION = "2025-06-18";
    private static final String SERVER_NAME = "PetProfile MCP Server";
    private static final String SERVER_VERSION = "0.2.4";
    /** Package-scoped broadcast sent after a successful MCP write so foreground screens refresh. */
    public static final String ACTION_DATA_CHANGED = "io.github.jaffe2718.petprofile.action.DATA_CHANGED";
    private static final int DEFAULT_PORT = 18999;
    private static final int SOCKET_TIMEOUT_MS = 30000;

    private static volatile McpServer instance;

    private final Context context;
    private final McpToolRegistry toolRegistry;
    private final Object lock = new Object();

    private volatile ServerSocket serverSocket;
    private volatile boolean running;
    private volatile int port;
    private ExecutorService executor;

    private McpServer(Context context) {
        this.context = context.getApplicationContext();
        this.toolRegistry = new McpToolRegistry(context);
    }

    public static McpServer get(Context context) {
        if (instance == null) {
            synchronized (McpServer.class) {
                if (instance == null) {
                    instance = new McpServer(context);
                }
            }
        }
        return instance;
    }

    public void start() {
        synchronized (lock) {
            if (running) {
                return;
            }
            running = true;
            executor = Executors.newCachedThreadPool();
            try {
                bindSocket();
            } catch (IOException e) {
                running = false;
                shutDownExecutor();
                return;
            }
            executor.execute(this::acceptLoop);
        }
    }

    public void stop() {
        synchronized (lock) {
            running = false;
            try {
                if (serverSocket != null) {
                    serverSocket.close();
                }
            } catch (IOException ignored) {
            }
            serverSocket = null;
            shutDownExecutor();
        }
    }

    public boolean isRunning() {
        return running;
    }

    public int getPort() {
        return port;
    }

    /** The endpoint URL shown to the agent, e.g. http://192.168.1.10:18999/petprofile. */
    public String getUrl() {
        String ip = NetworkUtil.getLocalIpAddress();
        String host = ip == null ? "127.0.0.1" : ip;
        return "http://" + host + ":" + port + "/petprofile";
    }

    public String getAuthToken() {
        return McpTokenManager.getToken(context);
    }

    private void bindSocket() throws IOException {
        serverSocket = new ServerSocket();
        serverSocket.setReuseAddress(true);
        try {
            serverSocket.bind(new InetSocketAddress(DEFAULT_PORT));
        } catch (IOException first) {
            // Fall back to an OS-assigned port if the fixed one is taken.
            serverSocket.bind(new InetSocketAddress(0));
        }
        port = serverSocket.getLocalPort();
    }

    private void acceptLoop() {
        while (running) {
            Socket socket = null;
            try {
                socket = serverSocket.accept();
                if (!running) {
                    break;
                }
                final Socket connection = socket;
                executor.execute(() -> handleConnection(connection));
            } catch (IOException ignored) {
                if (running) {
                    try {
                        Thread.sleep(100L);
                    } catch (InterruptedException interrupted) {
                        Thread.currentThread().interrupt();
                        break;
                    }
                } else {
                    break;
                }
            } catch (Throwable ignored) {
                // Keep serving even if a single connection fails.
            }
        }
    }

    private void handleConnection(Socket socket) {
        try (Socket s = socket) {
            s.setSoTimeout(SOCKET_TIMEOUT_MS);
            BufferedInputStream input = new BufferedInputStream(s.getInputStream());
            BufferedOutputStream output = new BufferedOutputStream(s.getOutputStream());
            String connection = "keep-alive";
            while (running) {
                HttpRequest request = readRequest(input);
                if (request == null) {
                    break;
                }
                connection = request.headers.getOrDefault("connection", "keep-alive");
                HttpResponse response = route(request);
                writeResponse(output, response);
                output.flush();
                if ("close".equalsIgnoreCase(connection) || request.path == null) {
                    break;
                }
                if (response.closeAfter) {
                    break;
                }
            }
        } catch (IOException ignored) {
            // Connection-level errors simply end the session.
        } catch (Throwable ignored) {
            // Never let a malformed client crash the server thread.
        }
    }

    private HttpResponse route(HttpRequest request) {
        if (request.path == null || !request.path.equals("/petprofile")) {
            return HttpResponse.text(404, "Not Found", "Not Found");
        }
        if ("OPTIONS".equalsIgnoreCase(request.method)) {
            // CORS preflight (harmless for native MCP clients).
            return HttpResponse.empty(204);
        }
        if (!"POST".equalsIgnoreCase(request.method)) {
            return HttpResponse.text(405, "Method Not Allowed", "Method Not Allowed");
        }
        String auth = request.headers.get("authorization");
        if (!isAuthorized(auth)) {
            return HttpResponse.text(401, "Unauthorized", "{\"jsonrpc\":\"2.0\",\"id\":null,\"error\":{\"code\":-32001,\"message\":\"Unauthorized\"}}");
        }
        if (request.body == null || request.body.isEmpty()) {
            return HttpResponse.text(400, "Bad Request", "Empty body");
        }
        return dispatch(request.body);
    }

    private boolean isAuthorized(String authorization) {
        String expected = McpTokenManager.getToken(context);
        if (authorization == null || expected == null) {
            return false;
        }
        String prefix = "Bearer ";
        String trimmed = authorization.trim();
        if (!trimmed.regionMatches(true, 0, prefix, 0, prefix.length())) {
            return false;
        }
        String bearer = trimmed.substring(prefix.length()).trim();
        return expected.equals(bearer);
    }

    private HttpResponse dispatch(String body) {
        JsonObject request;
        try {
            request = JsonParser.parseString(body).getAsJsonObject();
        } catch (Throwable t) {
            return HttpResponse.json(jsonRpcError(null, -32700, "Parse error"));
        }
        if (!request.has("method") || request.get("method").isJsonNull()) {
            return HttpResponse.json(jsonRpcError(idOf(request), -32600, "Invalid Request"));
        }
        String method = request.get("method").getAsString();
        Object id = idOf(request);

        JsonObject rpcResult;
        switch (method) {
            case "initialize": {
                JsonObject result = new JsonObject();
                result.addProperty("protocolVersion", PROTOCOL_VERSION);
                JsonObject capabilities = new JsonObject();
                JsonObject tools = new JsonObject();
                tools.addProperty("listChanged", false);
                capabilities.add("tools", tools);
                result.add("capabilities", capabilities);
                JsonObject serverInfo = new JsonObject();
                serverInfo.addProperty("name", SERVER_NAME);
                serverInfo.addProperty("version", SERVER_VERSION);
                result.add("serverInfo", serverInfo);
                return HttpResponse.json(jsonRpcResult(id, result));
            }
            case "notifications/initialized": {
                // Notification: no JSON-RPC response body is expected.
                return HttpResponse.empty(202);
            }
            case "ping": {
                return HttpResponse.json(jsonRpcResult(id, new JsonObject()));
            }
            case "tools/list": {
                JsonObject result = new JsonObject();
                result.add("tools", toolRegistry.toMcpList());
                return HttpResponse.json(jsonRpcResult(id, result));
            }
            case "tools/call": {
                rpcResult = toolRegistry.call(request);
                return HttpResponse.json(jsonRpcResult(id, rpcResult));
            }
            default:
                return HttpResponse.json(jsonRpcError(id, -32601, "Method not found: " + method));
        }
    }

    private static Object idOf(JsonObject request) {
        if (request.has("id") && !request.get("id").isJsonNull()) {
            com.google.gson.JsonElement el = request.get("id");
            if (el.isJsonPrimitive()) {
                if (el.getAsJsonPrimitive().isNumber()) {
                    return el.getAsLong();
                }
                return el.getAsString();
            }
        }
        return null;
    }

    private static JsonObject jsonRpcResult(Object id, JsonObject result) {
        JsonObject response = new JsonObject();
        response.addProperty("jsonrpc", "2.0");
        if (id instanceof Number) {
            addNumber(response, "id", ((Number) id).longValue());
        } else if (id != null) {
            response.addProperty("id", id.toString());
        } else {
            response.add("id", com.google.gson.JsonNull.INSTANCE);
        }
        response.add("result", result);
        return response;
    }

    private static JsonObject jsonRpcError(Object id, int code, String message) {
        JsonObject response = new JsonObject();
        response.addProperty("jsonrpc", "2.0");
        if (id instanceof Number) {
            addNumber(response, "id", ((Number) id).longValue());
        } else if (id != null) {
            response.addProperty("id", id.toString());
        } else {
            response.add("id", com.google.gson.JsonNull.INSTANCE);
        }
        JsonObject error = new JsonObject();
        error.addProperty("code", code);
        error.addProperty("message", message);
        response.add("error", error);
        return response;
    }

    private static void addNumber(JsonObject obj, String name, long value) {
        obj.addProperty(name, value);
    }

    // ----- minimal HTTP/1.1 -----

    private static final class HttpRequest {
        String method;
        String path;
        Map<String, String> headers = new HashMap<>();
        String body;
    }

    private static final class HttpResponse {
        final int status;
        final String contentType;
        final String content;
        final boolean closeAfter;

        HttpResponse(int status, String contentType, String content, boolean closeAfter) {
            this.status = status;
            this.contentType = contentType;
            this.content = content;
            this.closeAfter = closeAfter;
        }

        static HttpResponse json(String json) {
            return new HttpResponse(200, "application/json", json, false);
        }

        static HttpResponse json(JsonObject json) {
            return new HttpResponse(200, "application/json", json.toString(), false);
        }

        static HttpResponse text(int status, String message, String body) {
            return new HttpResponse(status, "text/plain", body == null ? message : body, false);
        }

        static HttpResponse empty(int status) {
            return new HttpResponse(status, null, "", false);
        }
    }

    private static HttpRequest readRequest(BufferedInputStream input) throws IOException {
        String requestLine = readLine(input);
        if (requestLine == null || requestLine.isEmpty()) {
            return null;
        }
        String[] parts = requestLine.split(" ");
        if (parts.length < 2) {
            return null;
        }
        HttpRequest request = new HttpRequest();
        request.method = parts[0];
        request.path = parts.length >= 2 ? parts[1] : null;
        int contentLength = 0;
        String line;
        while ((line = readLine(input)) != null && !line.isEmpty()) {
            int colon = line.indexOf(':');
            if (colon > 0) {
                String name = line.substring(0, colon).trim().toLowerCase();
                String value = line.substring(colon + 1).trim();
                request.headers.put(name, value);
                if ("content-length".equals(name)) {
                    try {
                        contentLength = Integer.parseInt(value);
                    } catch (NumberFormatException ignored) {
                    }
                }
            }
        }
        if (contentLength > 0) {
            byte[] bodyBytes = readExactly(input, contentLength);
            if (bodyBytes != null) {
                request.body = new String(bodyBytes, StandardCharsets.UTF_8);
            }
        }
        return request;
    }

    private static byte[] readExactly(BufferedInputStream input, int length) throws IOException {
        byte[] buffer = new byte[length];
        int read = 0;
        while (read < length) {
            int r = input.read(buffer, read, length - read);
            if (r < 0) {
                break;
            }
            read += r;
        }
        return read == length ? buffer : null;
    }

    private static String readLine(BufferedInputStream input) throws IOException {
        StringBuilder sb = new StringBuilder();
        int b;
        while ((b = input.read()) >= 0) {
            if (b == '\n') {
                break;
            }
            if (b != '\r') {
                sb.append((char) b);
            }
        }
        if (sb.length() == 0 && b < 0) {
            return null;
        }
        return sb.toString();
    }

    private static void writeResponse(OutputStream out, HttpResponse response) throws IOException {
        String statusText = statusText(response.status);
        StringBuilder head = new StringBuilder();
        head.append("HTTP/1.1 ").append(response.status).append(' ').append(statusText).append("\r\n");
        head.append("Access-Control-Allow-Origin: *\r\n");
        head.append("Access-Control-Allow-Headers: Authorization, Content-Type, MCP-Protocol-Version, Accept\r\n");
        head.append("Access-Control-Allow-Methods: POST, OPTIONS\r\n");
        if (response.contentType != null) {
            head.append("Content-Type: ").append(response.contentType).append("; charset=utf-8\r\n");
        }
        if (response.content != null) {
            head.append("Content-Length: ").append(response.content.getBytes(StandardCharsets.UTF_8).length).append("\r\n");
        } else {
            head.append("Content-Length: 0\r\n");
        }
        head.append("Connection: keep-alive\r\n\r\n");
        out.write(head.toString().getBytes(StandardCharsets.UTF_8));
        if (response.content != null) {
            out.write(response.content.getBytes(StandardCharsets.UTF_8));
        }
    }

    private static String statusText(int status) {
        switch (status) {
            case 200:
                return "OK";
            case 202:
                return "Accepted";
            case 400:
                return "Bad Request";
            case 401:
                return "Unauthorized";
            case 404:
                return "Not Found";
            case 405:
                return "Method Not Allowed";
            default:
                return "OK";
        }
    }

    private void shutDownExecutor() {
        if (executor != null) {
            executor.shutdownNow();
            executor = null;
        }
    }
}
